SELECT YEAR(SALES_DATE) AS YEAR,MONTH(SALES_DATE) AS MONTH,GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE  AS O
JOIN USER_INFO AS U
ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH,GENDER
ORDER BY YEAR, MONTH, GENDER
# YEAR	MONTH	GENDER	USERS
# 2022	1	1	49
# 2022	2	1	46
# 2022	3	0	7

# SELECT YEAR(b.SALES_DATE) AS YEAR, MONTH(b.SALES_DATE) AS MONTH, a.GENDER AS GENDER, count(DISTINCT a.USER_ID )AS USER
# FROM USER_INFO a JOIN ONLINE_SALE b
# ON a.USER_ID = b.USER_ID
# WHERE a.GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER
# YEAR	MONTH	GENDER	USER
# 2022	1	0	24
# 2022	1	1	25
# 2022	2	0	25
# 2022	2	1	21
# 2022	3	0	3
# 2022	3	1	4