SELECT U.USER_ID, U.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER AS U
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AS B
ON U.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES

# SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES, STATUS
#     FROM USED_GOODS_BOARD
#     GROUP BY WRITER_ID
#     HAVING STATUS = 'DONE' AND SUM(PRICE) >= 700000
    
# SELECT *, SUM(PRICE) FROM USED_GOODS_BOARD WHERE STATUS = 'DONE'GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000

# SELECT WRITER_ID, SUM(PRICE) FROM USED_GOODS_BOARD WHERE STATUS = 'DONE' GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000