# SELECT M.MEMBER_NAME,R.REVIEW_TEXT,R.REVIEW_DATE,SUM(REVIEW_SCORE) FROM REST_REVIEW AS R
# LEFT JOIN MEMBER_PROFILE AS M
# ON M.MEMBER_ID = R.MEMBER_ID
# GROUP BY R.MEMBER_ID
# ORDER BY SUM(REVIEW_SCORE) DESC
# LIMIT 1 
# SELECT * FROM REST_REVIEW

# SELECT M.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM REST_REVIEW AS R
# JOIN (
#     SELECT B.MEMBER_NAME, B.MEMBER_ID
#     FROM REST_REVIEW AS A
#     LEFT JOIN MEMBER_PROFILE AS B
#     ON B.MEMBER_ID = A.MEMBER_ID
#     GROUP BY A.MEMBER_ID
#     ORDER BY SUM(REVIEW_SCORE) DESC
#     LIMIT 1 
# ) AS M
# ON M.MEMBER_ID = R.MEMBER_ID
# ORDER BY REVIEW_DATE, REVIEW_TEXT

SELECT  M.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS M
ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY SUM(REVIEW_SCORE) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT