-- 코드를 입력하세요
SELECT 
	TITLE, 
    USED_GOODS_BOARD.BOARD_ID, 
    REPLY_ID, 
    USED_GOODS_REPLY.WRITER_ID, 
    USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY
LEFT JOIN USED_GOODS_BOARD
ON USED_GOODS_REPLY.BOARD_ID = USED_GOODS_BOARD.BOARD_ID AND
USED_GOODS_BOARD.CREATED_DATE <= '2022-10-31'
WHERE DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY CREATED_DATE, TITLE